[package]
name = "systemd-ddns"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
futures = { version = "0.3.31", default-features = false }
futures-rustls = "0.26.0"
http-body-util = "0.1.3"
hyper = { version = "1.6.0", default-features = false, features = ["client", "http1"] }
rtnetlink = { version = "0.17.0", default-features = false, features = ["smol_socket"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
smol = "2.0.2"
smol-hyper = "0.1.1"
tracing = "0.1.41"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
webpki-roots = "1.0.2"

[features]
default = []
test_gandi = []

[dev-dependencies]
macro_rules_attribute = "0.2.2"
smol-macros = "0.1.1"
test-log = "0.2.18"
tracing-test = "0.2.5"
