[package]
name = "systemd-ddns"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
futures = "0.3.31"
reqwest = { version = "0.12.22", features = ["json"] }
rtnetlink = "0.17.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
zbus = "5.9.0"
zbus_systemd = { version = "0.25701.0", features = ["network1"] }

[dev-dependencies]
tokio = { version = "1.46.1", features = ["fs"] }
tracing-test = "0.2.5"
